MODEL:
  NUM_CLASSES: 6
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'mobilenet_v2'
    OUT_CHANNELS: (96, 1280, 512, 256, 256, 64)
  PRIORS:
    FEATURE_MAPS: [20, 10, 5, 3, 2, 1]
    STRIDES: [16, 32, 64, 100, 150, 300]
    MIN_SIZES: [60, 105, 150, 195, 240, 285]
    MAX_SIZES: [105, 150, 195, 240, 285, 330]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
    BOXES_PER_LOCATION: [6, 6, 6, 6, 6, 6]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("custom_train",)
  TEST: ("custom_test",)
# Training set size: 1700 images
SOLVER: 
  #MAX_ITER: 120000
  #LR_STEPS: [80000, 100000]
  MAX_ITER: 260000
  LR_STEPS: [100000, 190000]
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-3

OUTPUT_DIR: 'outputs/mobilenet_v2_ssd320_custom'